ManagementUtiility/ManagementUtiility/Areas/Admin/Controllers/CompanyController.cs
using ManagementServices;
using ManagementViewModel;
using Microsoft.AspNetCore.Mvc;

namespace ManagementUtiility.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CompanyController : Controller
    {
        private ICompanyInfo _companyInfo;

        public CompanyController(ICompanyInfo companyInfo)
        {
            _companyInfo = companyInfo;
        }

        public IActionResult Index(int Pageno = 1,int pagesize=10)
        {
            return View(_companyInfo.GetAll(Pageno, pagesize));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel=_companyInfo.GetCompanyById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(CompanyInfoViewModel vm)
        {
            _companyInfo.UpdateCompanyInfo(vm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {
           
            return View();
        }

        [HttpPost]
        public IActionResult Create(CompanyInfoViewModel vm)
        {
            _companyInfo.InsertCompanyInfo(vm);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _companyInfo.DeleteCompanyInfo(id);
            return RedirectToAction("Index");
        }
    }
}

ManagementUtiility/ManagementUtiility/Areas/Admin/Controllers/ContactController.cs
using ManagemeantModel;
using ManagementServices;
using ManagementViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Contracts;

namespace ManagementUtiility.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ContactController : Controller
    {
        private IContact _contact;
        private ICompanyInfo _companyinfo;

        public ContactController(IContact contact, ICompanyInfo companyInfo)
        {
            _contact = contact;
            _companyinfo = companyInfo;
           
        }
        public IActionResult Index(int Pageno = 1, int pagesize = 10)
        {
            return View(_contact.GetAll(Pageno,pagesize));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _contact.GetContactById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(ContactViewModel vm)
        {
            _contact.UpdateContact(vm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {


            return View();
        }

        [HttpPost]
        public IActionResult Create(ContactViewModel vm)
        {
            _contact.InsertContact(vm);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _contact.DeleteContact(id);
            return RedirectToAction("Index");
        }
    }
}

ManagementUtiility/ManagementUtiility/Areas/Admin/Controllers/FacilityController.cs
using ManagemeantModel;
using ManagementServices;
using ManagementViewModel;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics.Contracts;

namespace ManagementUtiility.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class FacilityController : Controller
    {
        
        private ICompanyInfo _companyinfo;
        private IFacility _facility;

        public FacilityController(IFacility facility, ICompanyInfo companyInfo)
        {
            _facility = facility;
            _companyinfo = companyInfo;
        }
        public IActionResult Index(int Pageno = 1, int pagesize = 10)
        {
            return View(_facility.GetAll(Pageno,pagesize));
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            var viewModel = _facility.GetFacilityById(id);
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Edit(FacilityViewModel vm)
        {
            _facility.UpdateFacilityInfo(vm);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Create()
        {


            return View();
        }

        [HttpPost]
        public IActionResult Create(FacilityViewModel vm)
        {
            _facility.InsertFacilityInfo(vm);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int id)
        {
            _facility.DeleteFacilityInfo(id);
            return RedirectToAction("Index");
        }
    }
}

ManagementUtiility/ManagementUtiility/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ManagementUtiility</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ManagementUtiility.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ManagementUtiility</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Facility" asp-action="Index">Facility</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="Admin" asp-controller="Contact" asp-action="Index">Contact</a>
                        </li>
                        <li class="nav-item">
                            <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/UserRegister">AddUser</a>
                        </li>
                        <li class="nav-item">
                            <a id="manage" class="nav-link text-dark" asp-area="Identity" asp-page="/Account/Register">AddPublic</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - ManagementUtiility - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>